"""Credential setup endpoints.

Flow:
  1) Cousin installs APK, opens app first time.
  2) App generates a stable per-device user_id (UUID stored in EncryptedSharedPreferences).
  3) App shows a Settings screen, collects Webull email/password/2FA (or device_id +
     access_token + account_id pulled from a Webull session export).
  4) App POSTs to ``/api/v1/setup`` with the user_id and creds.
  5) Backend encrypts + persists. Future requests carry ``X-User-Id`` so the backend
     can look up creds on demand.
"""
from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Header, HTTPException, status
from pydantic import BaseModel, Field

from app.core.credentials import (
    CredentialStoreError,
    UserCredentials,
    get_store,
)

logger = logging.getLogger(__name__)

auth_router = APIRouter(tags=["auth"])


# ─── Request / response models ───────────────────────────────────────────────

class SetupRequest(BaseModel):
    """Credentials pushed from the Android app."""

    user_id: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="Stable per-device UUID generated by the Android client.",
    )
    webull_device_id: Optional[str] = Field(default=None, max_length=256)
    webull_access_token: Optional[str] = Field(default=None, max_length=4096)
    webull_refresh_token: Optional[str] = Field(default=None, max_length=4096)
    webull_account_id: Optional[str] = Field(default=None, max_length=128)
    anthropic_api_key: Optional[str] = Field(default=None, max_length=512)
    openai_api_key: Optional[str] = Field(default=None, max_length=512)


class SetupResponse(BaseModel):
    user_id: str
    has_webull: bool
    has_ai: bool
    message: str


class SetupStatusResponse(BaseModel):
    user_id: str
    configured: bool


# ─── Helpers ─────────────────────────────────────────────────────────────────

def require_user_id(x_user_id: Optional[str] = Header(default=None)) -> str:
    """FastAPI dependency — extract X-User-Id or 401."""
    if not x_user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing X-User-Id header. Open the app and complete Settings.",
        )
    if len(x_user_id) < 8 or len(x_user_id) > 128:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="X-User-Id is malformed.",
        )
    return x_user_id


# ─── Endpoints ───────────────────────────────────────────────────────────────

@auth_router.post("/setup", response_model=SetupResponse)
async def setup(request: SetupRequest) -> SetupResponse:
    """Save (or replace) a user's credentials."""
    creds = UserCredentials(
        user_id=request.user_id,
        webull_device_id=request.webull_device_id,
        webull_access_token=request.webull_access_token,
        webull_refresh_token=request.webull_refresh_token,
        webull_account_id=request.webull_account_id,
        anthropic_api_key=request.anthropic_api_key,
        openai_api_key=request.openai_api_key,
    )

    if not creds.as_dict():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Refusing to save an empty credential set.",
        )

    try:
        get_store().save(creds)
    except CredentialStoreError as exc:
        logger.exception("Credential store error during setup")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc

    return SetupResponse(
        user_id=creds.user_id,
        has_webull=bool(creds.webull_access_token and creds.webull_account_id),
        has_ai=bool(creds.anthropic_api_key or creds.openai_api_key),
        message="Credentials saved. You're ready to trade.",
    )


@auth_router.get("/setup/status", response_model=SetupStatusResponse)
async def setup_status(user_id: str = Header(..., alias="X-User-Id")) -> SetupStatusResponse:
    """Lightweight check the Android client uses to skip the setup screen."""
    try:
        configured = get_store().exists(user_id)
    except CredentialStoreError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
    return SetupStatusResponse(user_id=user_id, configured=configured)


@auth_router.delete("/setup", status_code=status.HTTP_204_NO_CONTENT)
async def delete_setup(user_id: str = Header(..., alias="X-User-Id")) -> None:
    """Wipe a user's stored credentials (Settings → Sign Out)."""
    try:
        get_store().delete(user_id)
    except CredentialStoreError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
